export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const ADD_PAGE = 'ADD_PAGE';
export const SELECT_PAGE = 'SELECT_PAGE'

export const ADD_TEXT = 'ADD_TEXT';

export const SELECT_COM = 'SELECT_COM'
export const STOP_DRAG = "STOP_DRAG"
export const STOP_RESIZE = "STOP_RESIZE"

export const CHANGE_ITEM_X = "CHANGE_ITEM_X"
export const CHANGE_ITEM_Y = "CHANGE_ITEM_Y"
export const CHANGE_ITEM_WIDTH = "CHANGE_ITEM_WIDTH"
export const CHANGE_ITEM_HEIGHT = "CHANGE_ITEM_HEIGHT"
export const CHANGE_ITEM_CONTENT = "CHANGE_ITEM_CONTENT"
export const CHANGE_ITEM_ANIMATION = "CHANGE_ITEM_ANIMATION"

export const CHANGE_ITEM_POSITION = "CHANGE_ITEM_POSITION"
export const CHANGE_ITEM_FONTSIZE = "CHANGE_ITEM_FONTSIZE"

export const TEXT_ALIGN_LEFT = "TEXT_ALIGN_LEFT"
export const TEXT_ALIGN_CENTER = "TEXT_ALIGN_CENTER"
export const TEXT_ALIGN_RIGHT = "TEXT_ALIGN_RIGHT"
export const TEXT_ITALIC = "TEXT_ITALIC"
export const TEXT_BOLD = "TEXT_BOLD"
export const TEXT_UNDERLINED = "TEXT_UNDERLINED"
